#!/bin/bash

set -e

export APPENGINE_SDK=$WERCKER_DEPLOY_GO_APPENGINE_APPENGINE_SDK
export GOROOT=$WERCKER_DEPLOY_GO_APPENGINE_GOROOT
export GOPATH=$WERCKER_DEPLOY_GO_APPENGINE_GOPATH

mkdir -p /src/$WERCKER_GIT_DOMAIN/$WERCKER_GIT_OWNER
ln -sfn $(pwd) /src/$WERCKER_GIT_DOMAIN/$WERCKER_GIT_OWNER/$WERCKER_GIT_REPOSITORY
$GOROOT/bin/goapp get -d $WERCKER_GIT_DOMAIN/$WERCKER_GIT_OWNER/$WERCKER_GIT_REPOSITORY/$WERCKER_DEPLOY_GO_APPENGINE_APP_PATH

gcloud auth activate-service-account --key-file $WERCKER_DEPLOY_GO_APPENGINE_KEY_FILE --project $WERCKER_DEPLOY_GO_APPENGINE_PROJECT
$APPENGINE_SDK/appcfg.py update app --oauth2_access_token $(gcloud auth print-access-token 2> /dev/null)
